### ISSUE TITLE
make use of PMB

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/schnitzler-tagebuch-static#15]
It would be nice if the indexentries would directly link to schnitzler-briefe and other resources, either via PMB or via a new listperson.xml -file that has both idnos in it, briefe and tagebuch

**Comment by csae8092** [comment]
hm, looks like you @martinantonmueller implemented this right now yourself?

**Comment by martinantonmueller** [comment]
yupp. not with places and organisations but than may do for now
