### ISSUE TITLE
search techniques change

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/schnitzler-tagebuch-static#17]
it is currently not possible to search with wildcards and jokers. will that be implemented? or do we have to communicate it?

**Comment by martinantonmueller** [comment]
It applies to wild card searches only. I've asked: https://github.com/projectEndings/staticSearch/issues/188

**Comment by martinantonmueller** [comment]
This was

**Comment by csae8092** [comment]
closing this issue as everything done on our side. when a new staticSearch version is released everything should wrok
