### ISSUE TITLE
Provide german translation for search captions

### ISSUE THREAD

**Issue by babslgam** [acdh-oeaw/schnitzler-tagebuch-static#19]
Captions for the search page are only available in English and French. They can be overwritten via js, as we do it now for removing the "Score" caption.
We should provide a german version for the captions.

|property| English  | German |
|-------------| ------------- | ------------- |
| strLoading  | Loading...  | lädt… |
| strSearching  | Searching...  | sucht… |
| strDocumentsFound | Documents found:   |Treffer: |
| PHRASE| Exact phrase:  | Exakte Formulierung:  |
| MUST_CONTAIN| Must contain:  | Muss enthalten: |
| MUST_NOT_CONTAIN| Must not contain:  | Darf nicht enthalten: |
| MAY_CONTAIN | May contain: | Kann enthalten: |
| WILDCARD | Wildcard term:   | Platzhalter: |
| strScore | Score:  | Rating: |
| strSearchTooBroad | Your search is too broad. Include more letters in every term.  | Die Suche ergibt zu viele Treffer. Bitte die Zeichenzahl im Wort erhöhen. |
| strDiscardedTerms | Not searched (too common or too short):  | Nicht gesucht (zu kurz oder zu allgemein):|
| strShowMore | Show more  | Mehr |
| strShowAll| Show all  | Zeige alles |
|strTooManyResults| Your search returned too many results. Include more filters or more search terms. | Die Suche ergibt zu viele Treffer. Durch Filterung oder Suchbegriffe einschränken. |
|ssDoSearch|Search| Suche|
|ssSearching|Searching...| Suche…|
|ssLoading|Loading...|Lade…|
|ssClear|Clear|Leeren|
|ssPoweredBy|Powered by|Bereitgestellt von|
|ssStartTyping|Start typing...|Zu tippen beginnen…|
|ssSearchIn|Search only in|Suche nur in|
|ssScriptRequired|This page requires JavaScript.|Diese Seite benötigt JavaScript.|

**Comment by babslgam** [comment]
i'm reopening this issue because i just found a second file where additional captions for the search page are coming from:
https://github.com/projectEndings/staticSearch/blob/dev/xsl/captions.xsl#L21-L28

**Comment by martinantonmueller** [comment]
Ich hab’ die weiteren Übersetzungen angelegt
