### ISSUE TITLE
Register – not working any more + order

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/schnitzler-tagebuch-static#21]
I would change the register tabs based in relevance, i.e.

Personen
Werke
Orte

because I believe most people (incl. myself) check for persons and works more often than places.

But as the the register is currently broken and is not showing anything it seems to be a detail… ;-)

**Comment by csae8092** [comment]
Someone (@martinantonmueller ) changed a bit the structure of the listperson and their XML IDs, which breaks a bit the code which I'll adapt next week so everything should be working again

**Comment by martinantonmueller** [comment]
I already feel guilty! :hangs head in shame:

**Comment by martinantonmueller** [comment]
I stand up for my errors and fixed listperson. now I hope this error will go away by itself. but to make listperson more future-proof i would prefer it if instead of /person/@xml:id the element person/idno[@type='schnitzler-tagegbuch'] would be used as reference identifier.

**Comment by csae8092** [comment]
the idno thing should possible be changed in the data; and the order of the tabs can't be changed (easy) because this breaks the map

**Comment by martinantonmueller** [comment]
I fixed it in the data. But as we are currently using similar listxxxx.xml in the different schnitzler-projects it makes sense to have them differentiate by the idnos and not the xml:ids as it‘s quicker to get new data deployed. Anyhoo, thanks!
