### ISSUE TITLE
Search results chronological?

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/schnitzler-tagebuch-static#23]
It would be desirable if the search results could be in chronological order because in a common scenario one is looking for the first appearance.

**Comment by csae8092** [comment]
not sure if this is

**Comment by babslgam** [comment]
https://endings.uvic.ca/staticSearch/docs/howDoIUseIt.html#configuringDocSortKey
https://acdh-oeaw.github.io/schnitzler-tagebuch-static/search.html?q=Feier
i guess that would be a feature request for StaticSearch since fulltext search results are ordered by score by default.

**Comment by martinantonmueller** [comment]
So maybe some filter possibilities i.e. all entries from a certain year could bypass that. I‘ll leave an issue though

**Comment by martinantonmueller** [comment]
This is the answer from @martindholmes: 

> We do have the document sort key feature:
> 
> https://endings.uvic.ca/staticSearch/docs/howDoIUseIt.html#configuringDocSortKey
> 
> If you create your sort keys as ISO dates, then they will naturally sort in order. However, this is normally overridden by the hit score, so to get a true date-based sort, you may have to override the method SSResultSet~sortByScoreDesc:
> 
> https://github.com/projectEndings/staticSearch/blob/v1.4.0/js/SSResultSet.js#L315

@csae8092, would you do the honors?

**Comment by csae8092** [comment]
closing this issue as we'll have a new search engine now/soon
