### ISSUE TITLE
make old URIs work again

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/schnitzler-tagebuch-static#29]
i.e.
https://schnitzler-tagebuch.acdh.oeaw.ac.at/entity/person_15984

**Comment by csae8092** [comment]
the application could provide https://schnitzler-tagebuch.acdh.oeaw.ac.at/entity/person_15984.html URIs but this would make the rather easy set up more complex; so we keep the existing ones -> https://schnitzler-tagebuch.acdh.oeaw.ac.at/person_15984.html
