### ISSUE TITLE
Unwanted text in index

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/schnitzler-tagebuch-static#34]
cf. https://schnitzler-tagebuch.acdh.oeaw.ac.at/person_19143.html
![Bildschirmfoto 2022-02-01 um 16 29 51](https://user-images.githubusercontent.com/11441262/151998273-248e8b9a-470d-492c-92d5-4b3ae03395cb.png)

**Comment by csae8092** [comment]
ok, this is a saxon issue
https://stackoverflow.com/questions/64466680/how-to-set-language-data-with-saxon-he-10-2

so for the time we will swatch back to good old iso-dates

**Comment by martinantonmueller** [comment]
This was solved with latest updated
