### ISSUE TITLE
overall css

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/schnitzler-tagebuch-static#7]
- [x] hover over buttons on https://acdh-oeaw.github.io/schnitzler-tagebuch-static/
- [x] nav bar not using whole screen width
- [x] have register closed as a standard https://github.com/acdh-oeaw/schnitzler-tagebuch-static/issues/8
- [x] remove shadow from central div, i.e. https://acdh-oeaw.github.io/schnitzler-tagebuch-static/work_1271.html. the way to go is that the text field is light gray. 
- [x] front page: the frames with images are uneven
- [x] front page: the title should align to the left
- [x] style the index entries (font sizes et. al.)
- [x] styling of the calendar: remove the unnecessary header bar for one year back and forth scrolling https://github.com/acdh-oeaw/schnitzler-tagebuch-static/issues/9
- [x] have the calendar year menu smaller as it used to be
- [x] have the +/- button not red/blue but some green version https://acdh-oeaw.github.io/schnitzler-tagebuch-static/listplace.html
- [x] front page left column uneven
- [x] Secondary menu: Menu partially in CAPITALS (ZITIEREN) partially with capital first letter (Register). This has to be one or the other. I suggest Capitals as PDF and TEI are already capitals.
- [x] Briefnetz should be BRIEFNETZ

**Comment by Shubham56-droid** [comment]
front page: the frames with images are uneven   -> can u pls assign this issue to me

**Comment by babslgam** [comment]
@Shubham56-droid hi and thanks, it should be fixed now.

**Comment by csae8092** [comment]
the last task would require to much work (or some javascript magic)

**Comment by martinantonmueller** [comment]
the date-thing could be solved with xlst 2: format-date()
